/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as EnSearchRouteImport } from './routes/en/search'
import { Route as EnResourcesRouteImport } from './routes/en/resources'
import { Route as EnNotesRouteImport } from './routes/en/notes'
import { Route as EnAboutRouteImport } from './routes/en/about'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as EnArticlesSlugRouteImport } from './routes/en/articles.$slug'
import { Route as ApiOgArticlesSlugRouteImport } from './routes/api.og.articles.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResourcesRoute,
} as any)
const EnSearchRoute = EnSearchRouteImport.update({
  id: '/en/search',
  path: '/en/search',
  getParentRoute: () => rootRouteImport,
} as any)
const EnResourcesRoute = EnResourcesRouteImport.update({
  id: '/en/resources',
  path: '/en/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const EnNotesRoute = EnNotesRouteImport.update({
  id: '/en/notes',
  path: '/en/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/en/about',
  path: '/en/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EnArticlesSlugRoute = EnArticlesSlugRouteImport.update({
  id: '/en/articles/$slug',
  path: '/en/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgArticlesSlugRoute = ApiOgArticlesSlugRouteImport.update({
  id: '/api/og/articles/$slug',
  path: '/api/og/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/notes': typeof NotesRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/en/about': typeof EnAboutRoute
  '/en/notes': typeof EnNotesRoute
  '/en/resources': typeof EnResourcesRoute
  '/en/search': typeof EnSearchRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/articles/': typeof ArticlesIndexRoute
  '/en/': typeof EnIndexRoute
  '/en/articles/$slug': typeof EnArticlesSlugRoute
  '/api/og/articles/$slug': typeof ApiOgArticlesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/notes': typeof NotesRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/en/about': typeof EnAboutRoute
  '/en/notes': typeof EnNotesRoute
  '/en/resources': typeof EnResourcesRoute
  '/en/search': typeof EnSearchRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/articles': typeof ArticlesIndexRoute
  '/en': typeof EnIndexRoute
  '/en/articles/$slug': typeof EnArticlesSlugRoute
  '/api/og/articles/$slug': typeof ApiOgArticlesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/notes': typeof NotesRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/en/about': typeof EnAboutRoute
  '/en/notes': typeof EnNotesRoute
  '/en/resources': typeof EnResourcesRoute
  '/en/search': typeof EnSearchRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/articles/': typeof ArticlesIndexRoute
  '/en/': typeof EnIndexRoute
  '/en/articles/$slug': typeof EnArticlesSlugRoute
  '/api/og/articles/$slug': typeof ApiOgArticlesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/llms.txt'
    | '/notes'
    | '/resources'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/account'
    | '/admin'
    | '/articles/$slug'
    | '/en/about'
    | '/en/notes'
    | '/en/resources'
    | '/en/search'
    | '/resources/$slug'
    | '/u/$username'
    | '/articles/'
    | '/en/'
    | '/en/articles/$slug'
    | '/api/og/articles/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/llms.txt'
    | '/notes'
    | '/resources'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/account'
    | '/admin'
    | '/articles/$slug'
    | '/en/about'
    | '/en/notes'
    | '/en/resources'
    | '/en/search'
    | '/resources/$slug'
    | '/u/$username'
    | '/articles'
    | '/en'
    | '/en/articles/$slug'
    | '/api/og/articles/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/llms.txt'
    | '/notes'
    | '/resources'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/articles/$slug'
    | '/en/about'
    | '/en/notes'
    | '/en/resources'
    | '/en/search'
    | '/resources/$slug'
    | '/u/$username'
    | '/articles/'
    | '/en/'
    | '/en/articles/$slug'
    | '/api/og/articles/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  NotesRoute: typeof NotesRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  EnAboutRoute: typeof EnAboutRoute
  EnNotesRoute: typeof EnNotesRoute
  EnResourcesRoute: typeof EnResourcesRoute
  EnSearchRoute: typeof EnSearchRoute
  UUsernameRoute: typeof UUsernameRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  EnIndexRoute: typeof EnIndexRoute
  EnArticlesSlugRoute: typeof EnArticlesSlugRoute
  ApiOgArticlesSlugRoute: typeof ApiOgArticlesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/en/search': {
      id: '/en/search'
      path: '/en/search'
      fullPath: '/en/search'
      preLoaderRoute: typeof EnSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/resources': {
      id: '/en/resources'
      path: '/en/resources'
      fullPath: '/en/resources'
      preLoaderRoute: typeof EnResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/notes': {
      id: '/en/notes'
      path: '/en/notes'
      fullPath: '/en/notes'
      preLoaderRoute: typeof EnNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/about': {
      id: '/en/about'
      path: '/en/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/en/articles/$slug': {
      id: '/en/articles/$slug'
      path: '/en/articles/$slug'
      fullPath: '/en/articles/$slug'
      preLoaderRoute: typeof EnArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/articles/$slug': {
      id: '/api/og/articles/$slug'
      path: '/api/og/articles/$slug'
      fullPath: '/api/og/articles/$slug'
      preLoaderRoute: typeof ApiOgArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ResourcesRouteChildren {
  ResourcesSlugRoute: typeof ResourcesSlugRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesSlugRoute: ResourcesSlugRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  NotesRoute: NotesRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  EnAboutRoute: EnAboutRoute,
  EnNotesRoute: EnNotesRoute,
  EnResourcesRoute: EnResourcesRoute,
  EnSearchRoute: EnSearchRoute,
  UUsernameRoute: UUsernameRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  EnIndexRoute: EnIndexRoute,
  EnArticlesSlugRoute: EnArticlesSlugRoute,
  ApiOgArticlesSlugRoute: ApiOgArticlesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
